In [ ]:
#获取询问函前后时间
import pandas as pd
import datetime
import baostock as bs
from datetime import timedelta
with open('上交所问询函.csv',encoding='utf-8') as f:
    df = pd.read_csv(f)
df['时间'] = pd.to_datetime(df['时间'])
df['时间']  = df['时间'].dt.date

In [ ]:
df_raw = pd.DataFrame(data=None, index=None, columns=['股票代码','第T天','第T-3天'], dtype=None, copy=False)

In [ ]:
bs.login()
for i in range(0,len(df)):
        df1 = df[['股票代码','时间']]
        stock_id ="sh."+str(df1['股票代码'][i])
        start_date = df1['时间'][i]
        end_date = start_date-timedelta(days = 10)
        #获取股票id,起始日期
        try:
            rs = bs.query_history_k_data_plus(stock_id,
    "date,code,close,preclose,adjustflag,turn,tradestatus,pctChg",
    start_date=str(end_date), end_date=str(start_date),
    frequency="d", adjustflag="3")
            data_list = []
            while (rs.error_code == '0') & rs.next():
                 data_list.append(rs.get_row_data())
            stock_dt1 = pd.DataFrame(data_list, columns=rs.fields)
            df2 = pd.DataFrame({'股票代码':stock_id,'第T天':stock_dt1.iloc[-4]['close'],'第T-3天':stock_dt1.iloc[-1]['close']},index = [0])
            df_raw = df_raw.append(df2,ignore_index = True)
            print('正在处理第'+str(i)+"条记录")
        except:
            df2 = pd.DataFrame({'股票代码':stock_id,'第T天':'error','第T-3天':'error'},index = [0])
            df_raw = df_raw.append(df2,ignore_index = True)
            print("第"+str(i)+"条记录出现问题")
# for i in list:
bs.logout()
df_raw

In [ ]:
i=174
df1 = df[['股票代码','时间']]
stock_id = df1['股票代码'][i]
start_date = df1['时间'][i]
end_date = start_date+timedelta(days = 10)
#获取股票id,起始日期
stock_dt1 = get_stock_history(str(stock_id),start_date,end_date)
stock_dt1
# df2 = pd.DataFrame({'股票代码':stock_id,'第T天':stock_dt1['Close'][0],'第T+3天':stock_dt1['Close'][3]},index = [0])
# df_raw = df_raw.append(df2,ignore_index = True)

In [ ]:
df_raw.to_csv('stock_pre.csv')

In [66]:
import baostock as bs
import pandas as pd

#### 登陆系统 ####
lg = bs.login()
rs = bs.query_history_k_data_plus("sh.600539",
    "date,code,close,preclose,volume,amount,adjustflag,turn,tradestatus,pctChg",
    start_date='2017-10-10', end_date='2017-10-20',
    frequency="d", adjustflag="3")
data_list = []
while (rs.error_code == '0') & rs.next():
     data_list.append(rs.get_row_data())
result = pd.DataFrame(data_list, columns=rs.fields)

#### 登出系统 ####
bs.logout()
result

login success!
logout success!

,date,code,close,preclose,volume,amount,adjustflag,turn,tradestatus,pctChg
0,2017-10-10,sh.600539,17.6400,17.5800,669337,11814479.0000,3,0.291016,1,0.341294
1,2017-10-11,sh.600539,17.5700,17.6400,470610,8272024.0000,3,0.204613,1,-0.396824
2,2017-10-12,sh.600539,17.5000,17.5700,595337,10423063.0000,3,0.258842,1,-0.398405
3,2017-10-13,sh.600539,17.5300,17.5000,237600,4166651.0000,3,0.103304,1,0.171432
4,2017-10-16,sh.600539,17.4300,17.5300,279200,4873694.0000,3,0.121391,1,-0.570453
5,2017-10-17,sh.600539,17.5500,17.4300,200630,3512712.0000,3,0.087230,1,0.688462
6,2017-10-18,sh.600539,17.2600,17.5500,516600,8958572.0000,3,0.224609,1,-1.652416
7,2017-10-19,sh.600539,17.3400,17.2600,600300,10361928.0000,3,0.261000,1,0.463499
8,2017-10-20,sh.600539,17.3800,17.3400,406720,7004551.0000,3,0.176835,1,0.230675